cosmin/stashy

README.md
README.rst
setup.py
stashy/branch_permissions.py
stashy/client.py
stashy/helpers.py
stashy/repos.py
tests/test_client.py

This time I implemented the branch_permissions api urls as an override of the core api url in the utilizing modifications in StashClient and ResourceBase.  The solution is extensible, though I don't love the fact that `stash.projects[PROJECT].repos[REPO].permissions` and `stash.projects[PROJECT].repos[REPO].permitted` are so close and mean completely different things.

Branch permissions -- take 2

---

stashy/allrepos.py
stashy/client.py

Adds basic support for the `/repos` URI, listing all available Stash
repositories.

Add Support For `/repos`

---

requirements.txt

Pinning the versions creates huge interoperability issues with other packages.

Allow later versions of the requirements.

---

stashy/pullrequests.py

`PullRequest.comments()` sounds like it would return a list of comments, but in fact it posts a new comment. Renaming it to `.comment()` more clearly indicates that this method performs an action.

Rename PullRequest.comments() to .comment()

---

stashy/client.py

Add `oauth` argument to `Stash` and `StashClient`. Didn't touch `stashy.connect` to keep it compatible.

Support OAuth authentication.

---

requirements.txt
stashy/pullrequests.py
tests/resources/api/1.0/merge.json
tests/test_pullrequests.py

PullRequest.can_merge method always return True if response code Ok. But in Stash doc https://developer.atlassian.com/static/rest/stash/3.11.3/stash-rest.html#idp111152 we can see json examle with response code 200 and "canMerge": false.

fix PullRequest.can_merge method

---

.travis.yml

Just testing what Travis would look like for 3.5 support
Dropping support for 3.2
reference: https://groups.google.com/forum/#!msg/pypa-dev/Ef0PF2ZGAv0/hrO4BHkOBQAJ
official EOL https://www.python.org/dev/peps/pep-0392/#lifespan

testing support for python 3.5, dropping 3.2

---

stashy/client.py

Without content type, Bitbucket stop POSTs with
c.a.p.r.c.s.j.XsrfResourceFilter XSRF checks failed
Same problem can be seen when using curl without
-H "Content-Type: application/json"

Set content type in header to fix XSRF validation problem

---

stashy/pullrequests.py
stashy/repos.py

Class was duplicated between pullrequestss.py (old & complete
implementation) and repos.py (new light implementation).
Merged both back into pullrequests.py.

Remove duplicated PullRequests class

---

.travis.yml
requirements.txt

Restricting enum34 installs by python version.

---

stashy/admin/users.py

First one just seemed to be wrong and refers to adding a user to a user!
Second one seems more in line with the method name and how is documented at https://docs.atlassian.com/DAC/rest/stash/1.1.1/stash-rest.html
Like the library, hope this is somewhat useful.

Minor tweaks to docstrings

---

stashy/client.py

Since Bitbucket 5.5 you can use "Personal access tokens" to use the API, see https://confluence.atlassian.com/bitbucketserver/personal-access-tokens-939515499.html
> Personal access tokens were added in Bitbucket Server 5.5 and can be used to replace passwords over https, or to authenticate using the Bitbucket Server REST API over Basic Auth. 
This PR adds the possibility to use such a token:
```
stash = Stash('https://bitbucket-server.local', token='foobar')
```

Add token authentication

---

stashy/repos.py

post -> put
in the bitbucket server v5.8.0 post creates a new repository, and put actually updates the existing one
https://docs.atlassian.com/bitbucket-server/rest/5.7.0/bitbucket-rest.html#idm45568365953232

fix repository renaming

---

stashy/pullrequests.py

Adding this option to enable filtering results by author.
BTW, Thanks for publishing this repo, very handy!

Add author filter option to pr.all

---

stashy/pullrequests.py

Updated calls to use new API:
/rest/api/1.0/projects/{projectKey}/repos/{repositorySlug}/pull-requests/{pullRequestId}/participants/{userSlug}

Fix pullrequest approve/unapprove

---

stashy/repos.py

Per https://developer.atlassian.com/static/rest/stash/3.11.2/stash-rest.html#idp1320704
Retrieving tags for a repository is a paged API. This matches previous changes to resolve fetch branches in a paged manner

Retrieving tags for a repository is a paginated resource

---

stashy/repos.py

#71 removing refs/heads prefix from origin branch. so the origin_branch can be any committish

#71 removing refs/heads prefix from origin branch

---

stashy/repos.py

Add function `get_commit_pull_requests` in the `Repository` class to access API endpoint 'projects/{projectKey}/repos/{repositorySlug}/commits/{commitId}/pull-requests'.

Add support for 'projects/{projectKey}/repos/{repositorySlug}/commits/{commitId}/pull-requests'

---

.travis.yml

Seems the default dist was upgraded from trusty to xenial
which doesn't support python 2.6 anymore.

.travis.yml: Attempt to fix python 2.6 tests

---

stashy/branch_permissions.py

Commit e42d343ec4732a4b6092f0edca4719ac3b6346ac increased
the API version from 1 to 2 but did not actually change
the code to use the 2.0 API. Implement this now:
- POST on an existing Restriction is not allowed anymore,
use delete/create instead in update()
- set type and matcher type correctly and add Enums to make the
possible choices clear
- support accessKeys
- refactor code to reduce code duplication
TODO:
- Discuss: Should update() sliently do a delete() or should I remove update() and force callers to do this explicitly?
- Update documentation

Fix branch_permissions to actually use 2.0 API

---

stashy/repos.py

This creates the capability for stashy users to easily reference the "Allow Forks" button in the BitBucket repo GUI through stashy. 
To set the "Allow Forks" setting as _checked_:
`<stashy_repo_object>.forkable = True`
To set the "Allow Forks" setting as _unchecked_:
`<stashy_repo_object>.forkable = False`
To reference the current state of the "Allow Forks" setting for a repo (returns boolean; True means "Allow Forks" is checked, False means "Allow Forks" is unchecked):
`current_setting = <stashy_repo_object>.forkable['forkable']`

Add "Allow Forks" repo setting put and get capability

---

stashy/repos.py

This modification to stashy will add the ability to allow users to modify or check the "Is Public" setting on a repository level through the API. 
To check current status of the repo's "Is Public" setting (returns boolean; True means it _is_ public, False means it _is not_ public):
`current_privacy = <stashy_repo_or_proj_object>.public`
To ensure the repo is Public:
`<stashy_repo_or_proj_object>.public = True`
To ensure the repo is Private:
`<stashy_repo_or_proj_object>.public = False`

Add "Is Public" Setting Modification Capability for Repos

---

stashy/helpers.py

If there are many changed files the bitbucket api doesn't not updating parameter 'isLastPage' (isLastPage is always False). The check of 'nextPageStart' paramets was added to avoid infinite loop here.

Fix Bitbucket bug for big changes.

---

stashy/permissions.py

Added new APIs for grant/revoke user and group permissions on both Projects and Repositories. 
Old APIs, grant() and revoke(), were not affected by the change.
Change was due to need of groups management and existing users' APIs inconsistency.

Additional Grant/Revok APIs

---

stashy/default_reviewers.py

The default_reviewers.py stashy file has been updated to foster greater default reviewer support. This update Allows the user to update or modify existing default reviewer settings by calling either of initialize_def_rev_condition, update_def_rev_condition or delete_def_rev_condition.

Extend stashy default reviewer support

---

stashy/pullrequests.py

This change will fix the following warnings:
```
$ python3 setup.py test
[...]
stashy/pullrequests.py:214: SyntaxWarning: "is not" with a literal. Did you mean "!="?
if parentCommentId is not -1:
stashy/pullrequests.py:218: SyntaxWarning: "is not" with a literal. Did you mean "!="?
if fileLine is not -1:
```

Fix two warnings about usage of "is not"

---

MANIFEST.in

Otherwise, users unpacking the sdist (source distribution) would not
be able to run the tests.

Include tests/ in the sdist

---

.gitignore
README.md
tox.ini

Users who want to run the tests would get this warning:
```
$ python3 setup.py test
running test
WARNING: Testing via this command is deprecated and will be removed in
a future version. Users looking for a generic test entry point
independent of test runner are encouraged to use tox.
```
Let's add a tox.ini to modernize this.

Add a tox.ini

---

stashy/repos.py

For example, this does not work because the :param directive does not
start a paragraph:
```python
"""
Returns detailed information about a given commit
:param commit: like "1c972ea39318a4b3ce99bc51ab03277138c586ea"
:return:
"""
```

Fix a few issues in docstrings reStructuredText

---

stashy/__init__.py
stashy/client.py

This enables the use of custom SSO authentication methods (such as Kerberos).

Added support for requests.auth

---

stashy/repos.py

The current support for default reviewers was limited to Stash Projects.  This commit adds the same capability to Stash repos.

Add default reviewer support to repos

---

.travis.yml
requirements.txt
setup.py
test-requirements.txt

The `mock` package is only needed in tests.
Update: tested in Travis-CI. See build job: https://travis-ci.com/github/mupdt/stashy/builds/204921023

Removes `mock` from install_requirements

---

stashy/repos.py

Two small improvements are proposed:
* Add Repository.get_sync() method
* Allow repo move() to rename as well (backwards-compatible)

Repo get_sync() and rename on move()

---

stashy/pullrequests.py

With an additional bool argument
the different URL address is used
to create blocker comments instead of normal comments
Signed-off-by: Zanker Gerd (XC-DX/EPL) <gerd.zanker@de.bosch.com>

Added support to create blocker-comments, called tasks in web UI.
