- stashy/projects.py
I also removed 'project' arg to project.update (since it's an instance method).
> Allow setting 'public' via project.update

- stashy/repos.py
Also fixed the branches of repositories, it was using the
response_or_error and self.paginate which failed.
> Added forking to the repositories

- stashy/client.py
- stashy/ssh.py
I have added support for /rest/ssh/1.0/keys GET. This enabled someone to download your ssh public key or a specified user's public key.
> Add support for the SSH rest api

- stashy/branch_permissions.py
- stashy/client.py
- stashy/helpers.py
The Branch perms stopped working with the last code I pushed . 
Sorry for the mess up :-1:
> [Urgent] Fixed Branch perms and Client Delete

- stashy/pullrequests.py
Can't create a pull-request without this fix.
> Import a type that was needed.

- stashy/pullrequests.py
Also was about to add "pull-request/[slug]/commits", but bumped into it being somehow broken in the API (https://jira.atlassian.com/browse/STASH-7643), so ended up using activities.
> Fixed activities and commits for pull requests

- stashy/pullrequests.py
I updated the `comment()` function based on https://developer.atlassian.com/static/rest/stash/3.11.3/stash-rest.html#idp1448560
> Implement additional pull request endpoints

- stashy/errors.py
Adds an AuthenticationException type to errors.py, for easy handling of Authentication exceptions.
> Adds an AuthenticationException

- stashy/ssh.py
This adds adding SSH keys per user and fixes getting them per specific user (#65).
> Add ssh.create, fix ssh.get

- stashy/pullrequests.py
passing the parameters in body request instead of query parameters when doing a post requests
> fix pull request merge post

- README.md
- README.rst
Minor readme update adding links.
> Updated readmes with link to rest api docs

- README.md
- README.rst
- stashy/repos.py
Get and set parameters:
Requires a minimum number of approvers
Requires all reviewers to approve the pull request
Requires all tasks to be resolved
Requires a minimum number of successful builds
https://confluence.atlassian.com/bitbucketserver/checks-for-merging-pull-requests-776640039.html
> Pull requests workflow

- stashy/pullrequests.py
needs a list of dicts with 'user' key not a list of users
same as: https://github.com/cosmin/stashy/blob/master/stashy/pullrequests.py#L247
> fix the update pull request 'reviewers' entry

- README.md
- README.rst
- stashy/client.py
- stashy/helpers.py
- stashy/repos.py
> add git tag create and delete

- stashy/projects.py
This adds support for the api path:
projects/{project slug}/settings/hooks
> Add support for projects/{project slug}/settings/hooks

- stashy/__init__.py
- stashy/client.py
* change documentation: remove a superfluous word
* Stash __init__: session can be arg instead of kwarg
> Misc fixes

- stashy/repos.py
Add diff method for retrieve a diff between two branches
> Add diff method

- README.md
- stashy/pullrequests.py
Implemented endpoint to be able to delete comment.
@cosmin  Implemented UT test is missing. Can you advice me how to do it?
> Add possibility to remove comment

- README.md
- stashy/repos.py
Implemented https://docs.atlassian.com/bitbucket-server/rest/6.10.1/bitbucket-repository-ref-sync-rest.html#idp5 method.
> Add possibility to synchronize repo

- README.md
- stashy/pullrequests.py
Add method for the update of the comment by its ID.
> Add possibility to update comment
